### ISSUE TITLE
Tweak Z2M availability settings

### ISSUE THREAD

**Issue by joshuaspence** [joshuaspence/home-assistant-config#36]
I want to use custom availability settings for Z2M but this isn't supported (see zigbee2mqtt/hassio-zigbee2mqtt#225). My desired configuration is:

```yaml
availability:
  active:
    timeout: 10
  passive:
    timeout: 60
```
